export { default as Account } from './Account'
export { default as Homepage } from './Home'
export { default as ResetPassword } from './ResetPassword'
export { default as SendOTP } from './SendOTP'
export { default as ChangePassword } from './ChangePassword'